-- Generated by tools/generate_catalog.py; do not hand-edit.
return {
    ['Absorb-ACC'] = {
        { npc = 'Mazween', zone = 'Aht Urhgan Whitegate', location = '(G-7)', notes = '44,000 Gil', x = 7, y = 7 },
    },
    ['Absorb-CHR'] = {
        { npc = 'Jabbar', zone = 'Port Bastok', location = '(F-6)', notes = '14,070 Gil Tenshodo Guild Merchant Open from 1:00 - 23:00 daily', x = 6, y = 6 },
        { npc = 'Chiyo', zone = 'Norg', location = '(I-8)', notes = '15,750 Gil Open from 09:00 - 23:00 daily', x = 9, y = 8 },
    },
    ['Absorb-MND'] = {
        { npc = 'Jabbar', zone = 'Port Bastok', location = '(F-6)', notes = '14,070 Gil Tenshodo Guild Merchant Open from 1:00 - 23:00 daily', x = 6, y = 6 },
        { npc = 'Chiyo', zone = 'Norg', location = '(I-8)', notes = '15,750 Gil Open from 09:00 - 23:00 daily', x = 9, y = 8 },
    },
    ['Absorb-TP'] = {
        { npc = 'Mazween', zone = 'Aht Urhgan Whitegate', location = '(G-7)', notes = '27,000 Gil', x = 7, y = 7 },
    },
    ['Addle'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '130,378 Gil', x = 8, y = 9 },
        { npc = 'Creepstix', zone = 'Lower Jeuno', location = '(H-9)', notes = '130,378 Gil', x = 8, y = 9 },
    },
    ['Adloquium'] = {
        { npc = 'Silke', zone = 'Bastok Markets (S)', location = '(L-10)', notes = '36,300 Gil', x = 12, y = 10 },
    },
    ['Advancing March'] = {
        { npc = 'Valeriano', zone = 'Port Bastok', location = '(K-8)', notes = '2,104 Gil First Place nation in Conquest only', x = 11, y = 8 },
        { npc = 'Valeriano', zone = 'Southern San d\'Oria', location = '(I-9)', notes = '2,104 Gil First Place nation in Conquest only', x = 9, y = 9 },
        { npc = 'Valeriano', zone = 'Windurst Woods', location = '(H-10)', notes = '2,104 Gil First Place nation in Conquest only', x = 8, y = 10 },
    },
    ['Adventurer\'s Dirge'] = {
        { npc = 'Harmodios', zone = 'Bastok Markets', location = '(K-10)', notes = '91,425 Gil', x = 11, y = 10 },
    },
    ['Aera'] = {
        { npc = 'Ledericus', zone = 'Western Adoulin', location = '(H-5)', notes = '26,600 Gil', x = 8, y = 5 },
    },
    ['Aera II'] = {
        { npc = 'Ledericus', zone = 'Western Adoulin', location = '(H-5)', notes = '556,800 Gil', x = 8, y = 5 },
    },
    ['Aero'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '331 Gil', x = 10, y = 8 },
        { npc = 'Aroro', zone = 'Port Windurst', location = '(H-8)', notes = '331 Gil', x = 8, y = 8 },
        { npc = 'Zaira', zone = 'Bastok Markets', location = '(H-5)', notes = '331 Gil', x = 8, y = 5 },
    },
    ['Aero II'] = {
        { npc = 'Hilkomu-Makimu', zone = 'Windurst Waters South', location = '(G-7)', notes = '12,236 Gil', x = 7, y = 7 },
        { npc = 'Chutarmire', zone = 'Selbina', location = '(H-9)', notes = '12,236 Gil', x = 8, y = 9 },
    },
    ['Aero III'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '27,744 Gil', x = 8, y = 9 },
        { npc = 'Mazween', zone = 'Aht Urhgan Whitegate', location = '(G-7)', notes = '27,744 Gil', x = 7, y = 7 },
    },
    ['Aero IV'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '131,750 Gil', x = 8, y = 9 },
    },
    ['Aero V'] = {
        { npc = 'Ezura-Romazura', zone = 'Windurst Waters (S)', location = '(H-8) (South Map)', notes = '144,875 Gil', x = 8, y = 8 },
    },
    ['Aeroga'] = {
        { npc = 'Hilkomu-Makimu', zone = 'Windurst Waters South', location = '(G-7)', notes = '4,239 Gil Windurst at least 2nd place in Conquest', x = 7, y = 7 },
        { npc = 'Chutarmire', zone = 'Selbina', location = '(H-9)', notes = '4,239 Gil', x = 8, y = 9 },
    },
    ['Aeroga II'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '19,800 Gil', x = 8, y = 9 },
    },
    ['Aeroga III'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '95,625 Gil', x = 8, y = 9 },
    },
    ['Aeroja'] = {
        { npc = 'Ezura-Romazura', zone = 'Windurst Waters (S)', location = '(H-8) (South Map)', notes = '185,240 Gil', x = 8, y = 8 },
    },
    ['Aisha: Ichi'] = {
        { npc = 'Solby-Maholby', zone = 'Norg', location = '(H-9)', notes = '79,380 Gil', x = 8, y = 9 },
    },
    ['Anemohelix'] = {
        { npc = 'Layton', zone = 'The Eldieme Necropolis (S)', location = '(J-8)', notes = '6,981 Gil', x = 10, y = 8 },
    },
    ['Animus Augeo'] = {
        { npc = 'Silke', zone = 'Bastok Markets (S)', location = '(L-10)', notes = '29,925 Gil', x = 12, y = 10 },
    },
    ['Animus Minuo'] = {
        { npc = 'Silke', zone = 'Bastok Markets (S)', location = '(L-10)', notes = '29,925 Gil', x = 12, y = 10 },
    },
    ['Aquaveil'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '368 Gil', x = 10, y = 8 },
        { npc = 'Kususu', zone = 'Port Windurst', location = '(H-8)', notes = '368 Gil', x = 8, y = 8 },
    },
    ['Arise'] = {
        { npc = 'Emporox', zone = 'Reisenjima - (Ingress #8)', location = '', notes = '10,000 Potpourri Must first trade 100 Merit Points to access the Pot-filler goodness category.' },
    },
    ['Army\'s Paeon'] = {
        { npc = 'Hortense', zone = 'Bastok Markets', location = '(K-10)', notes = '38 Gil', x = 11, y = 10 },
    },
    ['Army\'s Paeon II'] = {
        { npc = 'Hortense', zone = 'Bastok Markets', location = '(K-10)', notes = '328 Gil', x = 11, y = 10 },
    },
    ['Army\'s Paeon III'] = {
        { npc = 'Hortense', zone = 'Bastok Markets', location = '(K-10)', notes = '3,312 Gil', x = 11, y = 10 },
        { npc = 'Toji Mumosulah', zone = 'Kazham', location = '(I-8)', notes = '3,312 Gil', x = 9, y = 8 },
    },
    ['Army\'s Paeon IV'] = {
        { npc = 'Hortense', zone = 'Bastok Markets', location = '(K-10)', notes = '6,072 Gil', x = 11, y = 10 },
    },
    ['Army\'s Paeon VI'] = {
        { npc = 'Hortense', zone = 'Bastok Markets', location = '(K-10)', notes = '48,944 Gil', x = 11, y = 10 },
    },
    ['Aspir'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '12,850 Gil', x = 10, y = 8 },
    },
    ['Aspir II'] = {
        { npc = 'Mazween', zone = 'Aht Urhgan Whitegate', location = '(G-7)', notes = '79,800 Gil', x = 7, y = 7 },
    },
    ['Aurorastorm'] = {
        { npc = 'Layton', zone = 'The Eldieme Necropolis (S)', location = '(J-8)', notes = '11,440 Gil', x = 10, y = 8 },
    },
    ['Auspice'] = {
        { npc = 'Brave Ox', zone = 'Rabao', location = '(F-7)', notes = '30,967 Gil', x = 6, y = 7 },
    },
    ['Banish'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '143 Gil San d\'Oria at least 2nd place in Conquest', x = 10, y = 8 },
        { npc = 'Kususu', zone = 'Port Windurst', location = '(H-8)', notes = '143 Gil Windurst at least 2nd place in Conquest', x = 8, y = 8 },
        { npc = 'Sororo', zone = 'Bastok Markets', location = '(H-5)', notes = '143 Gil Bastok at least 2nd place in Conquest', x = 8, y = 5 },
    },
    ['Banish II'] = {
        { npc = 'Shohrun-Tuhrun', zone = 'Windurst Waters South', location = '(G-7)', notes = '8,280 Gil Windurst at least 2nd place in Conquest', x = 7, y = 7 },
        { npc = 'Quelpia', zone = 'Selbina', location = '(H-9)', notes = '8,280 Gil', x = 8, y = 9 },
    },
    ['Banish III'] = {
        { npc = 'Nilerouche', zone = 'Tavnazian Safehold', location = '(F-7)', notes = '66,000 Gil', x = 6, y = 7 },
        { npc = 'Mazuro-Oozuro', zone = 'Tavnazian Safehold', location = '(F-9)', notes = '66,000 Gil', x = 6, y = 9 },
        { npc = 'Brave Ox', zone = 'Rabao', location = '(F-7)', notes = '79,120 Gil', x = 6, y = 7 },
    },
    ['Banishga'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '1,191 Gil San d\'Oria at least 2nd place in Conquest', x = 10, y = 8 },
        { npc = 'Kususu', zone = 'Port Windurst', location = '(H-8)', notes = '1,191 Gil Bastok at least 2nd place in Conquest', x = 8, y = 8 },
        { npc = 'Sororo', zone = 'Bastok Markets', location = '(H-5)', notes = '1,191 Gil Bastok at least 2nd place in Conquest', x = 8, y = 5 },
    },
    ['Banishga II'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '20,000 Gil', x = 8, y = 9 },
        { npc = 'Zafif', zone = 'Al Zahbi', location = '(J-8)', notes = '20,000 Gil', x = 10, y = 8 },
    },
    ['Baraera'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '930 Gil', x = 8, y = 9 },
    },
    ['Baraero'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '930 Gil', x = 8, y = 9 },
    },
    ['Baramnesia'] = {
        { npc = 'Tya Padolih', zone = 'Mhaura', location = '(G-9)', notes = '27,820 Gil', x = 7, y = 9 },
    },
    ['Baramnesra'] = {
        { npc = 'Tya Padolih', zone = 'Mhaura', location = '(G-9)', notes = '27,820 Gil', x = 7, y = 9 },
    },
    ['Barblind'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '2,030 Gil', x = 8, y = 9 },
    },
    ['Barblindra'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '2,030 Gil', x = 8, y = 9 },
    },
    ['Barblizzara'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '3,624 Gil', x = 8, y = 9 },
    },
    ['Barblizzard'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '3,624 Gil', x = 8, y = 9 },
    },
    ['Barfira'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '1,760 Gil', x = 8, y = 9 },
    },
    ['Barfire'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '1,760 Gil', x = 8, y = 9 },
    },
    ['Barparalyze'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '780 Gil', x = 8, y = 9 },
    },
    ['Barparalyzra'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '780 Gil', x = 8, y = 9 },
    },
    ['Barpetra'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '15,120 Gil', x = 8, y = 9 },
    },
    ['Barpetrify'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '15,120 Gil', x = 8, y = 9 },
    },
    ['Barpoison'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '400 Gil', x = 8, y = 9 },
    },
    ['Barpoisonra'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '400 Gil', x = 8, y = 9 },
    },
    ['Barsilence'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '4,608 Gil', x = 8, y = 9 },
    },
    ['Barsilencera'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '4,608 Gil', x = 8, y = 9 },
    },
    ['Barsleep'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '244 Gil', x = 8, y = 9 },
    },
    ['Barsleepra'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '244 Gil', x = 8, y = 9 },
    },
    ['Barstone'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '156 Gil', x = 8, y = 9 },
    },
    ['Barstonra'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '156 Gil', x = 8, y = 9 },
    },
    ['Barthunder'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '5,754 Gil', x = 8, y = 9 },
    },
    ['Barthundra'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '5,754 Gil', x = 8, y = 9 },
    },
    ['Barvira'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '9,600 Gil', x = 8, y = 9 },
    },
    ['Barvirus'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '9,600 Gil', x = 8, y = 9 },
    },
    ['Barwater'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '360 Gil', x = 8, y = 9 },
    },
    ['Barwatera'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '360 Gil', x = 8, y = 9 },
    },
    ['Battlefield Elegy'] = {
        { npc = 'Thadiene', zone = 'Southern San d\'Oria', location = '(K-7)', notes = '4,416 Gil', x = 11, y = 7 },
    },
    ['Bewitching Etude'] = {
        { npc = 'Harmodios', zone = 'Bastok Markets', location = '(K-10)', notes = '55,200 Gil', x = 11, y = 10 },
    },
    ['Bio'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '368 Gil San d\'Oria at least 2nd place in Conquest', x = 10, y = 8 },
        { npc = 'Aroro', zone = 'Port Windurst', location = '(H-8)', notes = '368 Gil Windurst at least 2nd place in Conquest', x = 8, y = 8 },
        { npc = 'Zaira', zone = 'Bastok Markets', location = '(H-5)', notes = '368 Gil Bastok at least 2nd place in Conquest', x = 8, y = 5 },
    },
    ['Bio II'] = {
        { npc = 'Hilkomu-Makimu', zone = 'Windurst Waters South', location = '(G-7)', notes = '12,880 Gil Windurst must be in 1st place in Conquest AND Must be Windurst Citizen', x = 7, y = 7 },
        { npc = 'Mazween', zone = 'Aht Urhgan Whitegate', location = '(G-7)', notes = '14,000 Gil', x = 7, y = 7 },
        { npc = 'Chutarmire', zone = 'Selbina', location = '(H-9)', notes = '12,880 Gil', x = 8, y = 9 },
    },
    ['Bio III'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '139,125 Gil', x = 8, y = 9 },
    },
    ['Blaze Spikes'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '10,428 Gil', x = 10, y = 8 },
    },
    ['Blind'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '114 Gil San d\'Oria must be 1st place in Conquest AND Must be San d\'Oria Citizen', x = 10, y = 8 },
        { npc = 'Aroro', zone = 'Port Windurst', location = '(H-8)', notes = '114 Gil Windurst must be 1st place in Conquest AND Must be Windurst Citizen', x = 8, y = 8 },
        { npc = 'Zaira', zone = 'Bastok Markets', location = '(H-5)', notes = '114 Gil Bastok must be 1st place in Conquest AND Must be Bastok Citizen', x = 8, y = 5 },
    },
    ['Blind II'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '139,125 Gil', x = 8, y = 9 },
    },
    ['Blindna'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '1,012 Gil', x = 10, y = 8 },
        { npc = 'Kususu', zone = 'Port Windurst', location = '(H-8)', notes = '1,012 Gil', x = 8, y = 8 },
        { npc = 'Sororo', zone = 'Bastok Markets', location = '(H-5)', notes = '1,012 Gil', x = 8, y = 5 },
    },
    ['Blink'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '2,143 Gil San d\'Oria at least 2nd place in Conquest', x = 10, y = 8 },
        { npc = 'Kususu', zone = 'Port Windurst', location = '(H-8)', notes = '2,143 Gil Windurst at least 2nd place in Conquest', x = 8, y = 8 },
        { npc = 'Sororo', zone = 'Bastok Markets', location = '(H-5)', notes = '2,143 Gil Bastok at least 2nd place in Conquest', x = 8, y = 5 },
    },
    ['Blizzaga'] = {
        { npc = 'Hilkomu-Makimu', zone = 'Windurst Waters South', location = '(G-7)', notes = '10,948 Gil Windurst at least 2nd place in Conquest', x = 7, y = 7 },
        { npc = 'Chutarmire', zone = 'Selbina', location = '(H-9)', notes = '10,948 Gil', x = 8, y = 9 },
    },
    ['Blizzaga II'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '26,244 Gil', x = 8, y = 9 },
    },
    ['Blizzaga III'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '127,500 Gil', x = 8, y = 9 },
    },
    ['Blizzara'] = {
        { npc = 'Ledericus', zone = 'Western Adoulin', location = '(H-5)', notes = '46,440 Gil', x = 8, y = 5 },
    },
    ['Blizzara II'] = {
        { npc = 'Ledericus', zone = 'Western Adoulin', location = '(H-5)', notes = '652,800 Gil', x = 8, y = 5 },
    },
    ['Blizzard'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '1,619 Gil', x = 10, y = 8 },
        { npc = 'Aroro', zone = 'Port Windurst', location = '(H-8)', notes = '1,619 Gil', x = 8, y = 8 },
        { npc = 'Zaira', zone = 'Bastok Markets', location = '(H-5)', notes = '1,619 Gil', x = 8, y = 5 },
    },
    ['Blizzard II'] = {
        { npc = 'Hilkomu-Makimu', zone = 'Windurst Waters South', location = '(G-7)', notes = '22,356 Gil', x = 7, y = 7 },
        { npc = 'Chutarmire', zone = 'Selbina', location = '(H-9)', notes = '22,356 Gil', x = 8, y = 9 },
    },
    ['Blizzard III'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '39,368 Gil', x = 8, y = 9 },
        { npc = 'Mazween', zone = 'Aht Urhgan Whitegate', location = '(G-7)', notes = '39,368 Gil', x = 7, y = 7 },
    },
    ['Blizzard IV'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '166,250 Gil', x = 8, y = 9 },
    },
    ['Blizzard V'] = {
        { npc = 'Ezura-Romazura', zone = 'Windurst Waters (S)', location = '(H-8) (South Map)', notes = '186,375 Gil', x = 8, y = 8 },
    },
    ['Boost-AGI'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '85,680 Gil', x = 8, y = 9 },
        { npc = 'Creepstix', zone = 'Lower Jeuno', location = '(H-9)', notes = '85,680 Gil', x = 8, y = 9 },
    },
    ['Boost-CHR'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '81,900 Gil', x = 8, y = 9 },
        { npc = 'Creepstix', zone = 'Lower Jeuno', location = '(H-9)', notes = '81,900 Gil', x = 8, y = 9 },
    },
    ['Boost-DEX'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '99,613 Gil', x = 8, y = 9 },
    },
    ['Boost-INT'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '94,461 Gil', x = 8, y = 9 },
    },
    ['Boost-MND'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '77,500 Gil', x = 8, y = 9 },
        { npc = 'Creepstix', zone = 'Lower Jeuno', location = '(H-9)', notes = '77,500 Gil', x = 8, y = 9 },
    },
    ['Boost-STR'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '89,804 Gil', x = 8, y = 9 },
    },
    ['Boost-VIT'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '73,740 Gil', x = 8, y = 9 },
        { npc = 'Creepstix', zone = 'Lower Jeuno', location = '(H-9)', notes = '73,740 Gil', x = 8, y = 9 },
    },
    ['Break'] = {
        { npc = 'Ezura-Romazura', zone = 'Windurst Waters (S)', location = '(H-8) (South Map)', notes = '126,000 Gil', x = 8, y = 8 },
    },
    ['Burn'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '4,747 Gil', x = 10, y = 8 },
        { npc = 'Aroro', zone = 'Port Windurst', location = '(H-8)', notes = '4,747 Gil', x = 8, y = 8 },
        { npc = 'Zaira', zone = 'Bastok Markets', location = '(H-5)', notes = '4,747 Gil', x = 8, y = 5 },
    },
    ['Burst'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '63,750 Gil', x = 8, y = 9 },
    },
    ['Burst II'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '129,180 Gil', x = 8, y = 9 },
    },
    ['Chocobo Mazurka'] = {
        { npc = 'Ferdoulemiont', zone = 'Southern San d\'Oria', location = '(I-11)', notes = '50,784 Gil', x = 9, y = 11 },
        { npc = 'Neigepance', zone = 'Bastok Mines', location = '(J-9)', notes = '50,784 Gil', x = 10, y = 9 },
        { npc = 'Quesse', zone = 'Windurst Woods', location = '(K-12)', notes = '50,784 Gil', x = 11, y = 12 },
        { npc = 'Generoit', zone = 'Rabao', location = '(G-6)', notes = '50,784 Gil', x = 7, y = 6 },
        { npc = 'Mamerie', zone = 'Kazham', location = '(F-9)', notes = '50,784 Gil', x = 6, y = 9 },
    },
    ['Choke'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '2,300 Gil', x = 10, y = 8 },
        { npc = 'Aroro', zone = 'Port Windurst', location = '(H-8)', notes = '2,300 Gil', x = 8, y = 8 },
        { npc = 'Zaira', zone = 'Bastok Markets', location = '(H-5)', notes = '2,300 Gil', x = 8, y = 5 },
    },
    ['Crusade'] = {
        { npc = 'Brave Ox', zone = 'Rabao', location = '(F-7)', notes = '143,451 Gil', x = 6, y = 7 },
    },
    ['Cryohelix'] = {
        { npc = 'Layton', zone = 'The Eldieme Necropolis (S)', location = '(J-8)', notes = '7,896 Gil', x = 10, y = 8 },
    },
    ['Cura'] = {
        { npc = 'Brave Ox', zone = 'Rabao', location = '(F-7)', notes = '20,092 Gil', x = 6, y = 7 },
    },
    ['Cura II'] = {
        { npc = 'Brave Ox', zone = 'Rabao', location = '(F-7)', notes = '88,389 Gil', x = 6, y = 7 },
    },
    ['Curaga'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '1,393 Gil', x = 10, y = 8 },
        { npc = 'Kususu', zone = 'Port Windurst', location = '(H-8)', notes = '1,393 Gil', x = 8, y = 8 },
        { npc = 'Sororo', zone = 'Bastok Markets', location = '(H-5)', notes = '1,393 Gil', x = 8, y = 5 },
    },
    ['Curaga II'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '11,200 Gil', x = 8, y = 9 },
        { npc = 'Zafif', zone = 'Al Zahbi', location = '(J-8)', notes = '11,200 Gil', x = 10, y = 8 },
        { npc = 'Quelpia', zone = 'Selbina', location = '(H-9)', notes = '10,304 Gil', x = 8, y = 9 },
    },
    ['Curaga III'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '19,932 Gil', x = 8, y = 9 },
        { npc = 'Zafif', zone = 'Al Zahbi', location = '(J-8)', notes = '19,932 Gil', x = 10, y = 8 },
    },
    ['Cure'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '62 Gil', x = 10, y = 8 },
        { npc = 'Kususu', zone = 'Port Windurst', location = '(H-8)', notes = '62 Gil', x = 8, y = 8 },
        { npc = 'Sororo', zone = 'Bastok Markets', location = '(H-5)', notes = '62 Gil', x = 8, y = 5 },
    },
    ['Cure II'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '598 Gil San d\'Oria at least 2nd place in Conquest', x = 10, y = 8 },
        { npc = 'Kususu', zone = 'Port Windurst', location = '(H-8)', notes = '598 Gil Windurst at least 2nd place in Conquest', x = 8, y = 8 },
        { npc = 'Sororo', zone = 'Bastok Markets', location = '(H-5)', notes = '598 Gil Bastok at least 2nd place in Conquest', x = 8, y = 5 },
        { npc = 'Quelpia', zone = 'Selbina', location = '(H-9)', notes = '598 Gil', x = 8, y = 9 },
    },
    ['Cure III'] = {
        { npc = 'Shohrun-Tuhrun', zone = 'Windurst Waters South', location = '(G-7)', notes = '3,334 Gil', x = 7, y = 7 },
        { npc = 'Quelpia', zone = 'Selbina', location = '(H-9)', notes = '3,334 Gil', x = 8, y = 9 },
    },
    ['Cure IV'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '23,400 Gil', x = 8, y = 9 },
        { npc = 'Zafif', zone = 'Al Zahbi', location = '(J-8)', notes = '23,400 Gil', x = 10, y = 8 },
    },
    ['Cure VI'] = {
        { npc = 'Brave Ox', zone = 'Rabao', location = '(F-7)', notes = '141,137 Gil', x = 6, y = 7 },
    },
    ['Cursna'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '8,586 Gil', x = 8, y = 9 },
        { npc = 'Zafif', zone = 'Al Zahbi', location = '(J-8)', notes = '8,586 Gil', x = 10, y = 8 },
    },
    ['Dark Carol'] = {
        { npc = 'Yoskolo', zone = 'Lower Jeuno', location = '(I-8)', notes = '8,400 Gil', x = 9, y = 8 },
    },
    ['Dark Threnody'] = {
        { npc = 'Mjoll', zone = 'Bastok Markets', location = '(E-11)', notes = '199 Gil', x = 5, y = 11 },
    },
    ['Deodorize'] = {
        { npc = 'Tya Padolih', zone = 'Mhaura', location = '(G-9)', notes = '1,191 Gil', x = 7, y = 9 },
        { npc = 'Falgima', zone = 'Selbina', location = '(H-9)', notes = '1,191 Gil', x = 8, y = 9 },
    },
    ['Dextrous Etude'] = {
        { npc = 'Manyny', zone = 'Windurst Woods', location = '(H-13)', notes = '2,815 Gil', x = 8, y = 13 },
        { npc = 'Leyla', zone = 'Port Jeuno', location = '(H-8)', notes = '3,060 Gil', x = 8, y = 8 },
    },
    ['Dia'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '84 Gil', x = 10, y = 8 },
        { npc = 'Kususu', zone = 'Port Windurst', location = '(H-8)', notes = '84 Gil', x = 8, y = 8 },
        { npc = 'Sororo', zone = 'Bastok Markets', location = '(H-5)', notes = '84 Gil', x = 8, y = 5 },
    },
    ['Dia II'] = {
        { npc = 'Shohrun-Tuhrun', zone = 'Windurst Waters South', location = '(G-7)', notes = '10,304 Gil Windurst at least 2nd place in Conquest', x = 7, y = 7 },
        { npc = 'Quelpia', zone = 'Selbina', location = '(H-9)', notes = '10,304 Gil', x = 8, y = 9 },
    },
    ['Dia III'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '139,125 Gil', x = 8, y = 9 },
    },
    ['Diaga'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '1,191 Gil San d\'Oria must be 1st place in Conquest AND Must be San d\'Oria Citizen', x = 10, y = 8 },
        { npc = 'Kususu', zone = 'Port Windurst', location = '(H-8)', notes = '1,191 Gil Windurst must be 1st place in Conquest AND Must be Windurst Citizen', x = 8, y = 8 },
        { npc = 'Sororo', zone = 'Bastok Markets', location = '(H-5)', notes = '1,191 Gil Bastok must be 1st place in Conquest AND Must be Bastok Citizen', x = 8, y = 5 },
    },
    ['Dispel'] = {
        { npc = 'Shohrun-Tuhrun', zone = 'Windurst Waters South', location = '(G-7)', notes = '79,928 Gil', x = 7, y = 7 },
        { npc = 'Zafif', zone = 'Al Zahbi', location = '(J-8)', notes = '77,600 Gil', x = 10, y = 8 },
        { npc = 'Brave Ox', zone = 'Rabao', location = '(F-7)', notes = '64,400 Gil', x = 6, y = 7 },
    },
    ['Distract'] = {
        { npc = 'Tya Padolih', zone = 'Mhaura', location = '(G-9)', notes = '18,032~20,384 Gil', x = 7, y = 9 },
    },
    ['Distract II'] = {
        { npc = 'Nilerouche', zone = 'Tavnazian Safehold', location = '(F-7)', notes = '175,827 Gil', x = 6, y = 7 },
        { npc = 'Mazuro-Oozuro', zone = 'Tavnazian Safehold', location = '(F-9)', notes = '175,827 Gil', x = 6, y = 9 },
    },
    ['Dokumori: Ichi'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '2,849 Gil', x = 10, y = 8 },
    },
    ['Doton: Ichi'] = {
        { npc = 'Jabbar', zone = 'Port Bastok', location = '(F-6)', notes = '1,561 Gil Tenshodo Guild Merchant Open from 1:00 - 23:00 daily', x = 6, y = 6 },
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '2,331 Gil', x = 10, y = 8 },
        { npc = 'Chiyo', zone = 'Norg', location = '(I-8)', notes = '1,747 Gil', x = 9, y = 8 },
    },
    ['Doton: San'] = {
        { npc = 'Solby-Maholby', zone = 'Norg', location = '(H-9)', notes = '107,325 Gil', x = 8, y = 9 },
    },
    ['Drain'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '10,428 Gil', x = 10, y = 8 },
    },
    ['Drain II'] = {
        { npc = 'Mazween', zone = 'Aht Urhgan Whitegate', location = '(G-7)', notes = '30,780 Gil', x = 7, y = 7 },
    },
    ['Dread Spikes'] = {
        { npc = 'Mazween', zone = 'Aht Urhgan Whitegate', location = '(G-7)', notes = '70,560 Gil', x = 7, y = 7 },
    },
    ['Drown'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '6,508 Gil', x = 10, y = 8 },
        { npc = 'Aroro', zone = 'Port Windurst', location = '(H-8)', notes = '6,508 Gil', x = 8, y = 8 },
        { npc = 'Zaira', zone = 'Bastok Markets', location = '(H-5)', notes = '6,508 Gil', x = 8, y = 5 },
    },
    ['Earth Carol'] = {
        { npc = 'Yoskolo', zone = 'Lower Jeuno', location = '(I-8)', notes = '4,600 Gil', x = 9, y = 8 },
    },
    ['Earth Carol II'] = {
        { npc = 'Valeriano', zone = 'Port Bastok', location = '(K-8)', notes = '27,140 Gil First Place nation in Conquest only', x = 11, y = 8 },
        { npc = 'Valeriano', zone = 'Southern San d\'Oria', location = '(I-9)', notes = '27,140 Gil First Place nation in Conquest only', x = 9, y = 9 },
        { npc = 'Valeriano', zone = 'Windurst Woods', location = '(H-10)', notes = '27,140 Gil First Place nation in Conquest only', x = 8, y = 10 },
    },
    ['Earth Spirit'] = {
        { npc = 'Solby-Maholby', zone = 'Norg', location = '(H-9)', notes = '450-515 Gil', x = 8, y = 9 },
    },
    ['Earth Threnody'] = {
        { npc = 'Ensasa', zone = 'Windurst Waters North', location = '(H-9)', notes = '283 Gil', x = 8, y = 9 },
    },
    ['Enaero'] = {
        { npc = 'Shohrun-Tuhrun', zone = 'Windurst Waters South', location = '(G-7)', notes = '2,300 Gil Windurst at least 2nd place in Conquest', x = 7, y = 7 },
        { npc = 'Mamaroon', zone = 'Nashmau', location = '(H-7)', notes = '2,500 Gil', x = 8, y = 7 },
        { npc = 'Quelpia', zone = 'Selbina', location = '(H-9)', notes = '2,300 Gil', x = 8, y = 9 },
    },
    ['Enaero II'] = {
        { npc = 'Macchi Gazlitah', zone = 'Ru\'Lude Gardens', location = '(H-9)', notes = '27,968 Gil Tier 3 shop only', x = 8, y = 9 },
    },
    ['Enblizzard'] = {
        { npc = 'Shohrun-Tuhrun', zone = 'Windurst Waters South', location = '(G-7)', notes = '3,770 Gil Windurst at least 2nd place in Conquest', x = 7, y = 7 },
        { npc = 'Mamaroon', zone = 'Nashmau', location = '(H-7)', notes = '4,098 Gil', x = 8, y = 7 },
        { npc = 'Quelpia', zone = 'Selbina', location = '(H-9)', notes = '3,770 Gil', x = 8, y = 9 },
    },
    ['Enblizzard II'] = {
        { npc = 'Macchi Gazlitah', zone = 'Ru\'Lude Gardens', location = '(H-9)', notes = '30,492 Gil Tier 3 shop only', x = 8, y = 9 },
    },
    ['Enchanting Etude'] = {
        { npc = 'Manyny', zone = 'Windurst Woods', location = '(H-13)', notes = '1,000 Gil', x = 8, y = 13 },
        { npc = 'Leyla', zone = 'Port Jeuno', location = '(H-8)', notes = '1,088 Gil', x = 8, y = 8 },
    },
    ['Endark'] = {
        { npc = 'Mamaroon', zone = 'Nashmau', location = '(H-7)', notes = '100,800 Gil', x = 8, y = 7 },
    },
    ['Enfire'] = {
        { npc = 'Shohrun-Tuhrun', zone = 'Windurst Waters South', location = '(G-7)', notes = '4,747 Gil Windurst at least 2nd place in Conquest', x = 7, y = 7 },
        { npc = 'Mamaroon', zone = 'Nashmau', location = '(H-7)', notes = '5,160 Gil', x = 8, y = 7 },
        { npc = 'Quelpia', zone = 'Selbina', location = '(H-9)', notes = '4,747 Gil', x = 8, y = 9 },
    },
    ['Enfire II'] = {
        { npc = 'Macchi Gazlitah', zone = 'Ru\'Lude Gardens', location = '(H-9)', notes = '31,878 Gil Tier 3 shop only', x = 8, y = 9 },
    },
    ['Enlight'] = {
        { npc = 'Mamaroon', zone = 'Nashmau', location = '(H-7)', notes = '100,800 Gil', x = 8, y = 7 },
    },
    ['Enstone'] = {
        { npc = 'Shohrun-Tuhrun', zone = 'Windurst Waters South', location = '(G-7)', notes = '1,867 Gil Windurst at least 2nd place in Conquest', x = 7, y = 7 },
        { npc = 'Mamaroon', zone = 'Nashmau', location = '(H-7)', notes = '2,030 Gil', x = 8, y = 7 },
        { npc = 'Quelpia', zone = 'Selbina', location = '(H-9)', notes = '1,867 Gil', x = 8, y = 9 },
    },
    ['Enstone II'] = {
        { npc = 'Macchi Gazlitah', zone = 'Ru\'Lude Gardens', location = '(H-9)', notes = '26,112 Gil Tier 3 shop only', x = 8, y = 9 },
    },
    ['Enthunder'] = {
        { npc = 'Shohrun-Tuhrun', zone = 'Windurst Waters South', location = '(G-7)', notes = '1,393 Gil Windurst at least 2nd place in Conquest', x = 7, y = 7 },
        { npc = 'Mamaroon', zone = 'Nashmau', location = '(H-7)', notes = '1,515 Gil', x = 8, y = 7 },
        { npc = 'Quelpia', zone = 'Selbina', location = '(H-9)', notes = '1,393 Gil', x = 8, y = 9 },
    },
    ['Enthunder II'] = {
        { npc = 'Macchi Gazlitah', zone = 'Ru\'Lude Gardens', location = '(H-9)', notes = '25,600 Gil Tier 3 shop only', x = 8, y = 9 },
    },
    ['Enwater'] = {
        { npc = 'Shohrun-Tuhrun', zone = 'Windurst Waters South', location = '(G-7)', notes = '6,508 Gil Windurst at least 2nd place in Conquest', x = 7, y = 7 },
        { npc = 'Mamaroon', zone = 'Nashmau', location = '(H-7)', notes = '7,074 Gil', x = 8, y = 7 },
        { npc = 'Quelpia', zone = 'Selbina', location = '(H-9)', notes = '6,508 Gil', x = 8, y = 9 },
    },
    ['Enwater II'] = {
        { npc = 'Macchi Gazlitah', zone = 'Ru\'Lude Gardens', location = '(H-9)', notes = '33,000 Gil Tier 3 shop only', x = 8, y = 9 },
    },
    ['Esuna'] = {
        { npc = 'Brave Ox', zone = 'Rabao', location = '(F-7)', notes = '64,584 Gil', x = 6, y = 7 },
    },
    ['Fira'] = {
        { npc = 'Ledericus', zone = 'Western Adoulin', location = '(H-5)', notes = '34,000 Gil', x = 8, y = 5 },
    },
    ['Fira II'] = {
        { npc = 'Ledericus', zone = 'Western Adoulin', location = '(H-5)', notes = '604,800 Gil', x = 8, y = 5 },
    },
    ['Firaga'] = {
        { npc = 'Hilkomu-Makimu', zone = 'Windurst Waters South', location = '(G-7)', notes = '7,181 Gil Windurst at least 2nd place in Conquest', x = 7, y = 7 },
        { npc = 'Chutarmire', zone = 'Selbina', location = '(H-9)', notes = '7,181 Gil', x = 8, y = 9 },
    },
    ['Firaga II'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '21,307 Gil', x = 8, y = 9 },
    },
    ['Firaga III'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '112,000 Gil', x = 8, y = 9 },
    },
    ['Firaja'] = {
        { npc = 'Ezura-Romazura', zone = 'Windurst Waters (S)', location = '(H-8) (South Map)', notes = '193,800 Gil', x = 8, y = 8 },
    },
    ['Fire'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '855 Gil', x = 10, y = 8 },
        { npc = 'Aroro', zone = 'Port Windurst', location = '(H-8)', notes = '855 Gil', x = 8, y = 8 },
        { npc = 'Zaira', zone = 'Bastok Markets', location = '(H-5)', notes = '855 Gil', x = 8, y = 5 },
    },
    ['Fire Carol'] = {
        { npc = 'Yoskolo', zone = 'Lower Jeuno', location = '(I-8)', notes = '6,380 Gil', x = 9, y = 8 },
    },
    ['Fire Carol II'] = {
        { npc = 'Valeriano', zone = 'Port Bastok', location = '(K-8)', notes = '32,844 Gil First Place nation in Conquest only', x = 11, y = 8 },
        { npc = 'Valeriano', zone = 'Southern San d\'Oria', location = '(I-9)', notes = '32,844 Gil First Place nation in Conquest only', x = 9, y = 9 },
        { npc = 'Valeriano', zone = 'Windurst Woods', location = '(H-10)', notes = '32,844 Gil First Place nation in Conquest only', x = 8, y = 10 },
    },
    ['Fire II'] = {
        { npc = 'Hilkomu-Makimu', zone = 'Windurst Waters South', location = '(G-7)', notes = '16,928 Gil', x = 7, y = 7 },
        { npc = 'Chutarmire', zone = 'Selbina', location = '(H-9)', notes = '16,928 Gil', x = 8, y = 9 },
    },
    ['Fire III'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '33,306 Gil', x = 8, y = 9 },
        { npc = 'Mazween', zone = 'Aht Urhgan Whitegate', location = '(G-7)', notes = '33,306 Gil', x = 7, y = 7 },
    },
    ['Fire IV'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '148,500 Gil', x = 8, y = 9 },
    },
    ['Fire Threnody'] = {
        { npc = 'Ensasa', zone = 'Windurst Waters North', location = '(H-9)', notes = '644 Gil', x = 8, y = 9 },
    },
    ['Fire V'] = {
        { npc = 'Ezura-Romazura', zone = 'Windurst Waters (S)', location = '(H-8) (South Map)', notes = '162,500 Gil', x = 8, y = 8 },
    },
    ['Firestorm'] = {
        { npc = 'Layton', zone = 'The Eldieme Necropolis (S)', location = '(J-8)', notes = '8,060 Gil', x = 10, y = 8 },
    },
    ['Flare'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '71,250 Gil', x = 8, y = 9 },
    },
    ['Flare II'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '129,180 Gil', x = 8, y = 9 },
    },
    ['Flash'] = {
        { npc = 'Zafif', zone = 'Al Zahbi', location = '(J-8)', notes = '27,600 Gil', x = 10, y = 8 },
        { npc = 'Brave Ox', zone = 'Rabao', location = '(F-7)', notes = '32,200 Gil', x = 6, y = 7 },
    },
    ['Flood'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '67,500 Gil', x = 8, y = 9 },
    },
    ['Flood II'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '129,180 Gil', x = 8, y = 9 },
    },
    ['Flurry'] = {
        { npc = 'Falgima', zone = 'Selbina', location = '(H-9)', notes = '30,360 Gil', x = 8, y = 9 },
    },
    ['Flurry II'] = {
        { npc = 'Ledericus', zone = 'Western Adoulin', location = '(H-5)', notes = '396,825 Gil', x = 8, y = 5 },
    },
    ['Foe Lullaby II'] = {
        { npc = 'Toji Mumosulah', zone = 'Kazham', location = '(I-8)', notes = '64,528 Gil', x = 9, y = 8 },
    },
    ['Foe Requiem'] = {
        { npc = 'Hortense', zone = 'Bastok Markets', location = '(K-10)', notes = '66 Gil', x = 11, y = 10 },
    },
    ['Foe Requiem II'] = {
        { npc = 'Hortense', zone = 'Bastok Markets', location = '(K-10)', notes = '450 Gil', x = 11, y = 10 },
    },
    ['Foe Requiem III'] = {
        { npc = 'Hortense', zone = 'Bastok Markets', location = '(K-10)', notes = '4,048 Gil', x = 11, y = 10 },
    },
    ['Foe Requiem IV'] = {
        { npc = 'Hortense', zone = 'Bastok Markets', location = '(K-10)', notes = '7,065 Gil', x = 11, y = 10 },
    },
    ['Foe Requiem VII'] = {
        { npc = 'Hortense', zone = 'Bastok Markets', location = '(K-10)', notes = '47,196 Gil', x = 11, y = 10 },
    },
    ['Foe Sirvente'] = {
        { npc = 'Harmodios', zone = 'Bastok Markets', location = '(K-10)', notes = '91,425 Gil', x = 11, y = 10 },
    },
    ['Foil'] = {
        { npc = 'Ledericus', zone = 'Western Adoulin', location = '(H-5)', notes = '83,160 Gil', x = 8, y = 5 },
    },
    ['Fowl Aubade'] = {
        { npc = 'Valeriano', zone = 'Port Bastok', location = '(K-8)', notes = '2,980 Gil First Place nation in Conquest only', x = 11, y = 8 },
        { npc = 'Valeriano', zone = 'Southern San d\'Oria', location = '(I-9)', notes = '2,980 Gil First Place nation in Conquest only', x = 9, y = 9 },
        { npc = 'Valeriano', zone = 'Windurst Woods', location = '(H-10)', notes = '2,980 Gil First Place nation in Conquest only', x = 8, y = 10 },
    },
    ['Frazzle'] = {
        { npc = 'Tya Padolih', zone = 'Mhaura', location = '(G-9)', notes = '25,038~28,304 Gil', x = 7, y = 9 },
    },
    ['Frazzle II'] = {
        { npc = 'Nilerouche', zone = 'Tavnazian Safehold', location = '(F-7)', notes = '217,000 Gil', x = 6, y = 7 },
        { npc = 'Mazuro-Oozuro', zone = 'Tavnazian Safehold', location = '(F-9)', notes = '217,000 Gil', x = 6, y = 9 },
    },
    ['Freeze'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '52,500 Gil', x = 8, y = 9 },
    },
    ['Freeze II'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '129,180 Gil', x = 8, y = 9 },
    },
    ['Frost'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '3,770 Gil', x = 10, y = 8 },
        { npc = 'Aroro', zone = 'Port Windurst', location = '(H-8)', notes = '3,770 Gil', x = 8, y = 8 },
        { npc = 'Zaira', zone = 'Bastok Markets', location = '(H-5)', notes = '3,770 Gil', x = 8, y = 5 },
    },
    ['Gain-AGI'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '85,680 Gil', x = 8, y = 9 },
        { npc = 'Creepstix', zone = 'Lower Jeuno', location = '(H-9)', notes = '85,680 Gil', x = 8, y = 9 },
    },
    ['Gain-CHR'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '81,900 Gil', x = 8, y = 9 },
        { npc = 'Creepstix', zone = 'Lower Jeuno', location = '(H-9)', notes = '81,900 Gil', x = 8, y = 9 },
    },
    ['Gain-DEX'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '99,613 Gil', x = 8, y = 9 },
    },
    ['Gain-INT'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '94,461 Gil', x = 8, y = 9 },
    },
    ['Gain-MND'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '77,500 Gil', x = 8, y = 9 },
        { npc = 'Creepstix', zone = 'Lower Jeuno', location = '(H-9)', notes = '77,500 Gil', x = 8, y = 9 },
    },
    ['Gain-STR'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '89,804 Gil', x = 8, y = 9 },
    },
    ['Gain-VIT'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '73,740 Gil', x = 8, y = 9 },
        { npc = 'Creepstix', zone = 'Lower Jeuno', location = '(H-9)', notes = '73,740 Gil', x = 8, y = 9 },
    },
    ['Gekka: Ichi'] = {
        { npc = 'Solby-Maholby', zone = 'Norg', location = '(H-9)', notes = '140,319 Gil', x = 8, y = 9 },
    },
    ['Geohelix'] = {
        { npc = 'Layton', zone = 'The Eldieme Necropolis (S)', location = '(J-8)', notes = '6,591 Gil', x = 10, y = 8 },
    },
    ['Goblin Gavotte'] = {
        { npc = 'Creepstix', zone = 'Lower Jeuno', location = '(H-9)', notes = '8,160 Gil', x = 8, y = 9 },
    },
    ['Goddess\'s Hymnus'] = {
        { npc = 'Valeriano', zone = 'Port Bastok', location = '(K-8)', notes = '92,000 Gil First Place nation in Conquest only', x = 11, y = 8 },
        { npc = 'Valeriano', zone = 'Southern San d\'Oria', location = '(I-9)', notes = '92,000 Gil First Place nation in Conquest only', x = 9, y = 9 },
        { npc = 'Valeriano', zone = 'Windurst Woods', location = '(H-10)', notes = '92,000 Gil First Place nation in Conquest only', x = 8, y = 10 },
    },
    ['Godfry sandbox'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '139,125 Gil', x = 8, y = 9 },
    },
    ['Hailstorm'] = {
        { npc = 'Layton', zone = 'The Eldieme Necropolis (S)', location = '(J-8)', notes = '8,580 Gil', x = 10, y = 8 },
    },
    ['Haste'] = {
        { npc = 'Shohrun-Tuhrun', zone = 'Windurst Waters South', location = '(G-7)', notes = '18,400 Gil Windurst must be in 1st place in Conquest AND Must be Windurst Citizen', x = 7, y = 7 },
        { npc = 'Quelpia', zone = 'Selbina', location = '(H-9)', notes = '18,400 Gil', x = 8, y = 9 },
    },
    ['Haste II'] = {
        { npc = 'Ledericus', zone = 'Western Adoulin', location = '(H-5)', notes = '396,825 Gil', x = 8, y = 5 },
    },
    ['Herb Pastoral'] = {
        { npc = 'Wije Tiren', zone = 'Windurst Woods', location = '(I-8)', notes = '99 Gil', x = 9, y = 8 },
    },
    ['Herculean Etude'] = {
        { npc = 'Harmodios', zone = 'Bastok Markets', location = '(K-10)', notes = '81,328 Gil Bastok at least 2nd place in Conquest', x = 11, y = 10 },
    },
    ['Hojo: Ichi'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '2,849 Gil', x = 10, y = 8 },
    },
    ['Holy'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '35,000 Gil', x = 8, y = 9 },
        { npc = 'Zafif', zone = 'Al Zahbi', location = '(J-8)', notes = '35,000 Gil', x = 10, y = 8 },
        { npc = 'Quelpia', zone = 'Selbina', location = '(H-9)', notes = '32,200 Gil', x = 8, y = 9 },
    },
    ['Hunter\'s Prelude'] = {
        { npc = 'Mono Nchaa', zone = 'Windurst Woods', location = '(H-13)', notes = '2,649 Gil', x = 8, y = 13 },
    },
    ['Huton: Ichi'] = {
        { npc = 'Jabbar', zone = 'Port Bastok', location = '(F-6)', notes = '1,561 Gil Tenshodo Guild Merchant Open from 1:00 - 23:00 daily', x = 6, y = 6 },
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '2,331 Gil', x = 10, y = 8 },
        { npc = 'Chiyo', zone = 'Norg', location = '(I-8)', notes = '1,747 Gil', x = 9, y = 8 },
    },
    ['Huton: San'] = {
        { npc = 'Solby-Maholby', zone = 'Norg', location = '(H-9)', notes = '107,325 Gil', x = 8, y = 9 },
    },
    ['Hydrohelix'] = {
        { npc = 'Layton', zone = 'The Eldieme Necropolis (S)', location = '(J-8)', notes = '6,786 Gil', x = 10, y = 8 },
    },
    ['Hyoton: Ichi'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '2,331 Gil', x = 10, y = 8 },
        { npc = 'Chiyo', zone = 'Norg', location = '(I-8)', notes = '1,747 Gil', x = 9, y = 8 },
    },
    ['Hyoton: San'] = {
        { npc = 'Solby-Maholby', zone = 'Norg', location = '(H-9)', notes = '107,325 Gil', x = 8, y = 9 },
    },
    ['Ice Carol'] = {
        { npc = 'Yoskolo', zone = 'Lower Jeuno', location = '(I-8)', notes = '7,440 Gil', x = 9, y = 8 },
    },
    ['Ice Threnody'] = {
        { npc = 'Mjoll', zone = 'Bastok Markets', location = '(E-11)', notes = '1,000 Gil', x = 5, y = 11 },
    },
    ['Indi-Acumen'] = {
        { npc = 'Eukalline', zone = 'Western Adoulin', location = '(I-5)', notes = '52,080 Gil', x = 9, y = 5 },
    },
    ['Indi-AGI'] = {
        { npc = 'Ishvad', zone = 'Western Adoulin', location = '(I-5)', notes = '32,640 Gil', x = 9, y = 5 },
    },
    ['Indi-Attunement'] = {
        { npc = 'Ishvad', zone = 'Western Adoulin', location = '(I-5)', notes = '2,425 Gil', x = 9, y = 5 },
    },
    ['Indi-Barrier'] = {
        { npc = 'Ishvad', zone = 'Western Adoulin', location = '(I-5)', notes = '10,926 Gil', x = 9, y = 5 },
    },
    ['Indi-CHR'] = {
        { npc = 'Ishvad', zone = 'Western Adoulin', location = '(I-5)', notes = '21,000 Gil', x = 9, y = 5 },
    },
    ['Indi-DEX'] = {
        { npc = 'Ishvad', zone = 'Western Adoulin', location = '(I-5)', notes = '46,440 Gil', x = 9, y = 5 },
    },
    ['Indi-Fade'] = {
        { npc = 'Eukalline', zone = 'Western Adoulin', location = '(I-5)', notes = '703,800 Gil', x = 9, y = 5 },
    },
    ['Indi-Fend'] = {
        { npc = 'Ishvad', zone = 'Western Adoulin', location = '(I-5)', notes = '34,000 Gil', x = 9, y = 5 },
    },
    ['Indi-Focus'] = {
        { npc = 'Ishvad', zone = 'Western Adoulin', location = '(I-5)', notes = '6,692 Gil', x = 9, y = 5 },
    },
    ['Indi-Frailty'] = {
        { npc = 'Eukalline', zone = 'Western Adoulin', location = '(I-5)', notes = '537,030 Gil', x = 9, y = 5 },
    },
    ['Indi-Fury'] = {
        { npc = 'Ishvad', zone = 'Western Adoulin', location = '(I-5)', notes = '25,270 Gil', x = 9, y = 5 },
    },
    ['Indi-Gravity'] = {
        { npc = 'Eukalline', zone = 'Western Adoulin', location = '(I-5)', notes = '617,100 Gil', x = 9, y = 5 },
    },
    ['Indi-INT'] = {
        { npc = 'Ishvad', zone = 'Western Adoulin', location = '(I-5)', notes = '30,912 Gil', x = 9, y = 5 },
    },
    ['Indi-Languor'] = {
        { npc = 'Eukalline', zone = 'Western Adoulin', location = '(I-5)', notes = '94,185 Gil', x = 9, y = 5 },
    },
    ['Indi-Malaise'] = {
        { npc = 'Eukalline', zone = 'Western Adoulin', location = '(I-5)', notes = '617,100 Gil', x = 9, y = 5 },
    },
    ['Indi-MND'] = {
        { npc = 'Ishvad', zone = 'Western Adoulin', location = '(I-5)', notes = '23,940 Gil', x = 9, y = 5 },
    },
    ['Indi-Paralysis'] = {
        { npc = 'Eukalline', zone = 'Western Adoulin', location = '(I-5)', notes = '103,040 Gil', x = 9, y = 5 },
    },
    ['Indi-Poison'] = {
        { npc = 'Ishvad', zone = 'Western Adoulin', location = '(I-5)', notes = '100 Gil', x = 9, y = 5 },
    },
    ['Indi-Precision'] = {
        { npc = 'Ishvad', zone = 'Western Adoulin', location = '(I-5)', notes = '1,400 Gil', x = 9, y = 5 },
    },
    ['Indi-Refresh'] = {
        { npc = 'Ishvad', zone = 'Western Adoulin', location = '(I-5)', notes = '21,000 Gil', x = 9, y = 5 },
    },
    ['Indi-Regen'] = {
        { npc = 'Ishvad', zone = 'Western Adoulin', location = '(I-5)', notes = '2,335 Gil', x = 9, y = 5 },
    },
    ['Indi-Slip'] = {
        { npc = 'Eukalline', zone = 'Western Adoulin', location = '(I-5)', notes = '83,160 Gil', x = 9, y = 5 },
    },
    ['Indi-Slow'] = {
        { npc = 'Eukalline', zone = 'Western Adoulin', location = '(I-5)', notes = '53,460 Gil', x = 9, y = 5 },
    },
    ['Indi-STR'] = {
        { npc = 'Eukalline', zone = 'Western Adoulin', location = '(I-5)', notes = '53,460 Gil', x = 9, y = 5 },
    },
    ['Indi-Torpor'] = {
        { npc = 'Eukalline', zone = 'Western Adoulin', location = '(I-5)', notes = '61,875 Gil', x = 9, y = 5 },
    },
    ['Indi-Vex'] = {
        { npc = 'Eukalline', zone = 'Western Adoulin', location = '(I-5)', notes = '504,000 Gil', x = 9, y = 5 },
    },
    ['Indi-VIT'] = {
        { npc = 'Ishvad', zone = 'Western Adoulin', location = '(I-5)', notes = '43,740 Gil', x = 9, y = 5 },
    },
    ['Indi-Voidance'] = {
        { npc = 'Ishvad', zone = 'Western Adoulin', location = '(I-5)', notes = '372 Gil', x = 9, y = 5 },
    },
    ['Indi-Wilt'] = {
        { npc = 'Eukalline', zone = 'Western Adoulin', location = '(I-5)', notes = '576,300 Gil', x = 9, y = 5 },
    },
    ['Inundation'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '73,500 Gil', x = 8, y = 9 },
        { npc = 'Creepstix', zone = 'Lower Jeuno', location = '(H-9)', notes = '73,500 Gil', x = 8, y = 9 },
    },
    ['Invisible'] = {
        { npc = 'Tya Padolih', zone = 'Mhaura', location = '(G-9)', notes = '5,293 Gil', x = 7, y = 9 },
        { npc = 'Falgima', zone = 'Selbina', location = '(H-9)', notes = '5,293 Gil', x = 8, y = 9 },
    },
    ['Ionohelix'] = {
        { npc = 'Layton', zone = 'The Eldieme Necropolis (S)', location = '(J-8)', notes = '8,625 Gil', x = 10, y = 8 },
    },
    ['Jubaku: Ichi'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '2,849 Gil', x = 10, y = 8 },
    },
    ['Katon: Ichi'] = {
        { npc = 'Jabbar', zone = 'Port Bastok', location = '(F-6)', notes = '1,561 Gil Tenshodo Guild Merchant Open from 1:00 - 23:00 daily', x = 6, y = 6 },
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '2,331 Gil', x = 10, y = 8 },
        { npc = 'Chiyo', zone = 'Norg', location = '(I-8)', notes = '1,747 Gil', x = 9, y = 8 },
    },
    ['Katon: San'] = {
        { npc = 'Solby-Maholby', zone = 'Norg', location = '(H-9)', notes = '107,325 Gil', x = 8, y = 9 },
    },
    ['Klimaform'] = {
        { npc = 'Erlene', zone = 'The Eldieme Necropolis (S)', location = '(J-8)', notes = 'Quest: On Sabbatical', x = 10, y = 8 },
    },
    ['Knight\'s Minne'] = {
        { npc = 'Ferdoulemiont', zone = 'Southern San d\'Oria', location = '(I-11)', notes = '16 Gil', x = 9, y = 11 },
    },
    ['Knight\'s Minne II'] = {
        { npc = 'Ferdoulemiont', zone = 'Southern San d\'Oria', location = '(I-11)', notes = '883 Gil', x = 9, y = 11 },
    },
    ['Knight\'s Minne III'] = {
        { npc = 'Ferdoulemiont', zone = 'Southern San d\'Oria', location = '(I-11)', notes = '5,626 Gil', x = 9, y = 11 },
    },
    ['Knight\'s Minne V'] = {
        { npc = 'Ferdoulemiont', zone = 'Southern San d\'Oria', location = '(I-11)', notes = '50,692 Gil', x = 9, y = 11 },
    },
    ['Kurayami: Ichi'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '2,849 Gil', x = 10, y = 8 },
    },
    ['Learned Etude'] = {
        { npc = 'Manyny', zone = 'Windurst Woods', location = '(H-13)', notes = '1,567 Gil', x = 8, y = 13 },
        { npc = 'Leyla', zone = 'Port Jeuno', location = '(H-8)', notes = '1,704 Gil', x = 8, y = 8 },
    },
    ['Light Carol'] = {
        { npc = 'Yoskolo', zone = 'Lower Jeuno', location = '(I-8)', notes = '4,200 Gil', x = 9, y = 8 },
    },
    ['Light Threnody'] = {
        { npc = 'Lusiane', zone = 'Southern San d\'Oria', location = '(F-8)', notes = '110 Gil', x = 6, y = 8 },
    },
    ['Lightning Carol'] = {
        { npc = 'Yoskolo', zone = 'Lower Jeuno', location = '(I-8)', notes = '7,920 Gil', x = 9, y = 8 },
    },
    ['Logical Etude'] = {
        { npc = 'Harmodios', zone = 'Bastok Markets', location = '(K-10)', notes = '57,960 Gil Bastok at least 2nd place in Conquest', x = 11, y = 10 },
    },
    ['Ltng. Threnody'] = {
        { npc = 'Lusiane', zone = 'Southern San d\'Oria', location = '(F-8)', notes = '1,265 Gil', x = 6, y = 8 },
    },
    ['Luminohelix'] = {
        { npc = 'Layton', zone = 'The Eldieme Necropolis (S)', location = '(J-8)', notes = '8,940 Gil', x = 10, y = 8 },
    },
    ['Mage\'s Ballad'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '11,833 Gil', x = 10, y = 8 },
    },
    ['Mage\'s Ballad III'] = {
        { npc = 'Valeriano', zone = 'Port Bastok', location = '(K-8)', notes = '123,880 Gil First Place nation in Conquest only', x = 11, y = 8 },
        { npc = 'Valeriano', zone = 'Southern San d\'Oria', location = '(I-9)', notes = '123,880 Gil First Place nation in Conquest only', x = 9, y = 9 },
        { npc = 'Valeriano', zone = 'Windurst Woods', location = '(H-10)', notes = '123,880 Gil First Place nation in Conquest only', x = 8, y = 10 },
    },
    ['Meteor'] = {
        { npc = 'Emporox', zone = 'Reisenjima - (Ingress #8)', location = '', notes = '10,000 Potpourri Must first trade 100 Merit Points to access the Pot-filler goodness category.' },
    },
    ['Migawari: Ichi'] = {
        { npc = 'Solby-Maholby', zone = 'Norg', location = '(H-9)', notes = '133,053 Gil', x = 8, y = 9 },
    },
    ['Monomi: Ichi'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-9)', notes = '9,590 Gil', x = 10, y = 9 },
        { npc = 'Toji Mumosulah', zone = 'Kazham', location = '(I-8)', notes = '8,822 Gil', x = 9, y = 8 },
    },
    ['Myoshu: Ichi'] = {
        { npc = 'Solby-Maholby', zone = 'Norg', location = '(H-9)', notes = '84,766 Gil', x = 8, y = 9 },
    },
    ['Noctohelix'] = {
        { npc = 'Layton', zone = 'The Eldieme Necropolis (S)', location = '(J-8)', notes = '8,790 Gil', x = 10, y = 8 },
    },
    ['Paralyna'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '331 Gil', x = 10, y = 8 },
        { npc = 'Kususu', zone = 'Port Windurst', location = '(H-8)', notes = '331 Gil', x = 8, y = 8 },
        { npc = 'Sororo', zone = 'Bastok Markets', location = '(H-5)', notes = '331 Gil', x = 8, y = 5 },
    },
    ['Paralyze II'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '139,125 Gil', x = 8, y = 9 },
    },
    ['Phalanx II'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '139,125 Gil', x = 8, y = 9 },
    },
    ['Poison'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '84 Gil San d\'Oria at least 2nd place in Conquest', x = 10, y = 8 },
        { npc = 'Aroro', zone = 'Port Windurst', location = '(H-8)', notes = '84 Gil Windurst at least 2nd place in Conquest', x = 8, y = 8 },
        { npc = 'Zaira', zone = 'Bastok Markets', location = '(H-5)', notes = '84 Gil Bastok at least 2nd place in Conquest', x = 8, y = 5 },
    },
    ['Poison II'] = {
        { npc = 'Hilkomu-Makimu', zone = 'Windurst Waters South', location = '(G-7)', notes = '23,184 Gil Windurst must be in 1st place in Conquest AND Must be Windurst Citizen', x = 7, y = 7 },
        { npc = 'Mazween', zone = 'Aht Urhgan Whitegate', location = '(G-7)', notes = '25,200 Gil', x = 7, y = 7 },
        { npc = 'Chutarmire', zone = 'Selbina', location = '(H-9)', notes = '23,184 Gil', x = 8, y = 9 },
    },
    ['Poisona'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '184 Gil', x = 10, y = 8 },
        { npc = 'Kususu', zone = 'Port Windurst', location = '(H-8)', notes = '184 Gil', x = 8, y = 8 },
        { npc = 'Sororo', zone = 'Bastok Markets', location = '(H-5)', notes = '184 Gil', x = 8, y = 5 },
    },
    ['Poisonga'] = {
        { npc = 'Hilkomu-Makimu', zone = 'Windurst Waters South', location = '(G-7)', notes = '4,747 Gil Windurst must be in 1st place in Conquest AND Must be Windurst Citizen', x = 7, y = 7 },
        { npc = 'Mazween', zone = 'Aht Urhgan Whitegate', location = '(G-7)', notes = '5,160 Gil', x = 7, y = 7 },
        { npc = 'Chutarmire', zone = 'Selbina', location = '(H-9)', notes = '4,747 Gil', x = 8, y = 9 },
    },
    ['Protect'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '224 Gil', x = 10, y = 8 },
        { npc = 'Kususu', zone = 'Port Windurst', location = '(H-8)', notes = '224 Gil', x = 8, y = 8 },
        { npc = 'Sororo', zone = 'Bastok Markets', location = '(H-5)', notes = '224 Gil', x = 8, y = 5 },
    },
    ['Protect II'] = {
        { npc = 'Shohrun-Tuhrun', zone = 'Windurst Waters South', location = '(G-7)', notes = '6,508 Gil Windurst at least 2nd place in Conquest', x = 7, y = 7 },
        { npc = 'Quelpia', zone = 'Selbina', location = '(H-9)', notes = '6,508 Gil', x = 8, y = 9 },
    },
    ['Protect III'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '32,000 Gil', x = 8, y = 9 },
        { npc = 'Zafif', zone = 'Al Zahbi', location = '(J-8)', notes = '32,000 Gil', x = 10, y = 8 },
    },
    ['Protect IV'] = {
        { npc = 'Shohrun-Tuhrun', zone = 'Windurst Waters South', location = '(G-7)', notes = '92,000 Gil', x = 7, y = 7 },
        { npc = 'Zafif', zone = 'Al Zahbi', location = '(J-8)', notes = '91,116 Gil', x = 10, y = 8 },
        { npc = 'Brave Ox', zone = 'Rabao', location = '(F-7)', notes = '78,200 Gil', x = 6, y = 7 },
    },
    ['Protect V'] = {
        { npc = 'Brave Ox', zone = 'Rabao', location = '(F-7)', notes = '106,191 Gil', x = 6, y = 7 },
    },
    ['Protectra II'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '7,047 Gil', x = 8, y = 9 },
        { npc = 'Creepstix', zone = 'Lower Jeuno', location = '(H-9)', notes = '7,074 Gil', x = 8, y = 9 },
    },
    ['Protectra III'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '19,200 Gil', x = 8, y = 9 },
    },
    ['Protectra IV'] = {
        { npc = 'Shohrun-Tuhrun', zone = 'Windurst Waters South', location = '(G-7)', notes = '87,400 Gil', x = 7, y = 7 },
        { npc = 'Zafif', zone = 'Al Zahbi', location = '(J-8)', notes = '85,500 Gil', x = 10, y = 8 },
        { npc = 'Brave Ox', zone = 'Rabao', location = '(F-7)', notes = '83,810 Gil', x = 6, y = 7 },
    },
    ['Protectra V'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '119,240 Gil', x = 8, y = 9 },
    },
    ['Puppet\'s Operetta'] = {
        { npc = 'Valeriano', zone = 'Port Bastok', location = '(K-8)', notes = '17,296 Gil First Place nation in Conquest only', x = 11, y = 8 },
        { npc = 'Valeriano', zone = 'Southern San d\'Oria', location = '(I-9)', notes = '17,296 Gil First Place nation in Conquest only', x = 9, y = 9 },
        { npc = 'Valeriano', zone = 'Windurst Woods', location = '(H-10)', notes = '17,296 Gil First Place nation in Conquest only', x = 8, y = 10 },
    },
    ['Pyrohelix'] = {
        { npc = 'Layton', zone = 'The Eldieme Necropolis (S)', location = '(J-8)', notes = '7,714 Gil', x = 10, y = 8 },
    },
    ['Quake'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '60,000 Gil', x = 8, y = 9 },
    },
    ['Quake II'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '129,180 Gil', x = 8, y = 9 },
    },
    ['Quick Etude'] = {
        { npc = 'Manyny', zone = 'Windurst Woods', location = '(H-13)', notes = '1,913 Gil', x = 8, y = 13 },
        { npc = 'Leyla', zone = 'Port Jeuno', location = '(H-8)', notes = '2,080 Gil', x = 8, y = 8 },
    },
    ['Rainstorm'] = {
        { npc = 'Layton', zone = 'The Eldieme Necropolis (S)', location = '(J-8)', notes = '6,318 Gil', x = 10, y = 8 },
    },
    ['Raise'] = {
        { npc = 'Shohrun-Tuhrun', zone = 'Windurst Waters South', location = '(G-7)', notes = '5,293 Gil Windurst at least 2nd place in Conquest', x = 7, y = 7 },
        { npc = 'Quelpia', zone = 'Selbina', location = '(H-9)', notes = '5,293 Gil', x = 8, y = 9 },
    },
    ['Raiton: Ichi'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '2,331 Gil', x = 10, y = 8 },
        { npc = 'Chiyo', zone = 'Norg', location = '(I-8)', notes = '1,747 Gil', x = 9, y = 8 },
    },
    ['Raiton: San'] = {
        { npc = 'Solby-Maholby', zone = 'Norg', location = '(H-9)', notes = '107,325 Gil', x = 8, y = 9 },
    },
    ['Raptor Mazurka'] = {
        { npc = 'Khaf Jhifanm', zone = 'Aht Urhgan Whitegate', location = '(H-11)', notes = '4,400 Gil', x = 8, y = 11 },
    },
    ['Rasp'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '1,867 Gil', x = 10, y = 8 },
        { npc = 'Aroro', zone = 'Port Windurst', location = '(H-8)', notes = '1,867 Gil', x = 8, y = 8 },
        { npc = 'Zaira', zone = 'Bastok Markets', location = '(H-5)', notes = '1,867 Gil', x = 8, y = 5 },
    },
    ['Recall-Jugner'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '60,750 Gil', x = 10, y = 8 },
    },
    ['Recall-Meriph'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '60,750 Gil', x = 10, y = 8 },
    },
    ['Recall-Pashh'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '60,750 Gil', x = 10, y = 8 },
    },
    ['Refresh II'] = {
        { npc = 'Macchi Gazlitah', zone = 'Ru\'Lude Gardens', location = '(H-9)', notes = '150,000 Gil Tier 3 shop only', x = 8, y = 9 },
    },
    ['Regen'] = {
        { npc = 'Tya Padolih', zone = 'Mhaura', location = '(G-9)', notes = '3,974 Gil', x = 7, y = 9 },
    },
    ['Regen II'] = {
        { npc = 'Tya Padolih', zone = 'Mhaura', location = '(G-9)', notes = '7,203 Gil', x = 7, y = 9 },
    },
    ['Regen IV'] = {
        { npc = 'Gekko', zone = 'Port Jeuno', location = '(H-8)', notes = '50,400 Gil', x = 8, y = 8 },
    },
    ['Repose'] = {
        { npc = 'Sororo', zone = 'Bastok Markets', location = '(H-5)', notes = '30,360 Gil', x = 8, y = 5 },
    },
    ['Reprisal'] = {
        { npc = 'Zafif', zone = 'Al Zahbi', location = '(J-8)', notes = '28,500 Gil', x = 10, y = 8 },
    },
    ['Reraise III'] = {
        { npc = 'Dabih Jajalioh', zone = 'Ru\'Lude Gardens', location = '(F-9)', notes = '500,000 Gil Tier 4 shop only', x = 6, y = 9 },
        { npc = 'Zafif', zone = 'Al Zahbi', location = '(J-8)', notes = '99,375 Gil', x = 10, y = 8 },
        { npc = 'Brave Ox', zone = 'Rabao', location = '(F-7)', notes = '552,000 Gil', x = 6, y = 7 },
    },
    ['Retrace'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '32,320 Gil', x = 10, y = 8 },
    },
    ['Sacrifice'] = {
        { npc = 'Brave Ox', zone = 'Rabao', location = '(F-7)', notes = '62,192 Gil', x = 6, y = 7 },
    },
    ['Sage Etude'] = {
        { npc = 'Harmodios', zone = 'Bastok Markets', location = '(K-10)', notes = '64,768 Gil Bastok at least 2nd place in Conquest', x = 11, y = 10 },
    },
    ['Sandstorm'] = {
        { npc = 'Layton', zone = 'The Eldieme Necropolis (S)', location = '(J-8)', notes = '5,200 Gil', x = 10, y = 8 },
    },
    ['Scop\'s Operetta'] = {
        { npc = 'Valeriano', zone = 'Port Bastok', location = '(K-8)', notes = '598 Gil First Place nation in Conquest only', x = 11, y = 8 },
        { npc = 'Valeriano', zone = 'Southern San d\'Oria', location = '(I-9)', notes = '598 Gil First Place nation in Conquest only', x = 9, y = 9 },
        { npc = 'Valeriano', zone = 'Windurst Woods', location = '(H-10)', notes = '598 Gil First Place nation in Conquest only', x = 8, y = 10 },
    },
    ['Sentinel\'s Scherzo'] = {
        { npc = 'Yoskolo', zone = 'Lower Jeuno', location = '(I-8)', notes = '60,000 Gil', x = 9, y = 8 },
    },
    ['Sheepfoe Mambo'] = {
        { npc = 'Dohdjuma', zone = 'Selbina', location = '(G-10)', notes = '238 Gil', x = 7, y = 10 },
    },
    ['Shell'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '1,619 Gil', x = 10, y = 8 },
        { npc = 'Kususu', zone = 'Port Windurst', location = '(H-8)', notes = '1,619 Gil', x = 8, y = 8 },
        { npc = 'Sororo', zone = 'Bastok Markets', location = '(H-5)', notes = '1,619 Gil', x = 8, y = 5 },
    },
    ['Shell II'] = {
        { npc = 'Shohrun-Tuhrun', zone = 'Windurst Waters South', location = '(G-7)', notes = '16,192 Gil Windurst at least 2nd place in Conquest', x = 7, y = 7 },
        { npc = 'Quelpia', zone = 'Selbina', location = '(H-9)', notes = '16,192 Gil', x = 8, y = 9 },
    },
    ['Shell III'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '26,244 Gil', x = 8, y = 9 },
    },
    ['Shell V'] = {
        { npc = 'Brave Ox', zone = 'Rabao', location = '(F-7)', notes = '125,069 Gil', x = 6, y = 7 },
    },
    ['Shellra'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '1,760 Gil', x = 8, y = 9 },
        { npc = 'Creepstix', zone = 'Lower Jeuno', location = '(H-9)', notes = '1,760 Gil', x = 8, y = 9 },
    },
    ['Shellra II'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '14,080 Gil', x = 8, y = 9 },
    },
    ['Shellra III'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '26,244 Gil', x = 8, y = 9 },
    },
    ['Shellra V'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '124,540 Gil', x = 8, y = 9 },
    },
    ['Shock'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '1,393 Gil', x = 10, y = 8 },
        { npc = 'Aroro', zone = 'Port Windurst', location = '(H-8)', notes = '1,393 Gil', x = 8, y = 8 },
        { npc = 'Zaira', zone = 'Bastok Markets', location = '(H-5)', notes = '1,393 Gil', x = 8, y = 5 },
    },
    ['Shock Spikes'] = {
        { npc = 'Hilkomu-Makimu', zone = 'Windurst Waters South', location = '(G-7)', notes = '8,280 Gil Windurst at least 2nd place in Conquest', x = 7, y = 7 },
        { npc = 'Mamaroon', zone = 'Nashmau', location = '(H-7)', notes = '9,000 Gil', x = 8, y = 7 },
        { npc = 'Chutarmire', zone = 'Selbina', location = '(H-9)', notes = '8,280 Gil', x = 8, y = 9 },
    },
    ['Silena'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '2,330 Gil', x = 8, y = 9 },
        { npc = 'Zafif', zone = 'Al Zahbi', location = '(J-8)', notes = '2,330 Gil', x = 10, y = 8 },
    },
    ['Sinewy Etude'] = {
        { npc = 'Manyny', zone = 'Windurst Woods', location = '(H-13)', notes = '3,146 Gil', x = 8, y = 13 },
        { npc = 'Leyla', zone = 'Port Jeuno', location = '(H-8)', notes = '3,420 Gil', x = 8, y = 8 },
    },
    ['Sleep'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '2,300 Gil San d\'Oria at least 2nd place in Conquest', x = 10, y = 8 },
        { npc = 'Aroro', zone = 'Port Windurst', location = '(H-8)', notes = '2,300 Gil Windurst at least 2nd place in Conquest', x = 8, y = 8 },
        { npc = 'Zaira', zone = 'Bastok Markets', location = '(H-5)', notes = '2,300 Gil Bastok at least 2nd place in Conquest', x = 8, y = 5 },
    },
    ['Sleep II'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '18,720 Gil', x = 8, y = 9 },
        { npc = 'Mazween', zone = 'Aht Urhgan Whitegate', location = '(G-7)', notes = '18,720 Gil', x = 7, y = 7 },
    },
    ['Sleepga'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '11,200 Gil', x = 8, y = 9 },
        { npc = 'Mazween', zone = 'Aht Urhgan Whitegate', location = '(G-7)', notes = '11,200 Gil', x = 7, y = 7 },
        { npc = 'Tya Padolih', zone = 'Mhaura', location = '(G-9)', notes = '10,304 Gil', x = 7, y = 9 },
    },
    ['Sleepga II'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '67,818 Gil', x = 10, y = 8 },
    },
    ['Slow'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '855 Gil San d\'Oria must be 1st place in Conquest AND Must be San d\'Oria Citizen', x = 10, y = 8 },
        { npc = 'Kususu', zone = 'Port Windurst', location = '(H-8)', notes = '855 Gil Windurst must be 1st place in Conquest AND Must be Windurst Citizen', x = 8, y = 8 },
        { npc = 'Sororo', zone = 'Bastok Markets', location = '(H-5)', notes = '855 Gil Bastok must be 1st place in Conquest AND Must be Bastok Citizen', x = 8, y = 5 },
    },
    ['Slow II'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '139,125 Gil', x = 8, y = 9 },
    },
    ['Sneak'] = {
        { npc = 'Tya Padolih', zone = 'Mhaura', location = '(G-9)', notes = '2,300 Gil', x = 7, y = 9 },
        { npc = 'Falgima', zone = 'Selbina', location = '(H-9)', notes = '2,300 Gil', x = 8, y = 9 },
    },
    ['Spirited Etude'] = {
        { npc = 'Manyny', zone = 'Windurst Woods', location = '(H-13)', notes = '1,265 Gil', x = 8, y = 13 },
        { npc = 'Leyla', zone = 'Port Jeuno', location = '(H-8)', notes = '1,376 Gil', x = 8, y = 8 },
    },
    ['Stona'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '19,200 Gil', x = 8, y = 9 },
        { npc = 'Zafif', zone = 'Al Zahbi', location = '(J-8)', notes = '19,200 Gil', x = 10, y = 8 },
    },
    ['Stone'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '62 Gil', x = 10, y = 8 },
        { npc = 'Aroro', zone = 'Port Windurst', location = '(H-8)', notes = '62 Gil', x = 8, y = 8 },
        { npc = 'Zaira', zone = 'Bastok Markets', location = '(H-5)', notes = '62 Gil', x = 8, y = 5 },
    },
    ['Stone II'] = {
        { npc = 'Hilkomu-Makimu', zone = 'Windurst Waters South', location = '(G-7)', notes = '5,878 Gil', x = 7, y = 7 },
        { npc = 'Chutarmire', zone = 'Selbina', location = '(H-9)', notes = '5,878 Gil', x = 8, y = 9 },
    },
    ['Stone III'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '19,932 Gil', x = 8, y = 9 },
        { npc = 'Mazween', zone = 'Aht Urhgan Whitegate', location = '(G-7)', notes = '19,932 Gil', x = 7, y = 7 },
    },
    ['Stone IV'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '108,000 Gil', x = 8, y = 9 },
    },
    ['Stone V'] = {
        { npc = 'Ezura-Romazura', zone = 'Windurst Waters (S)', location = '(H-8) (South Map)', notes = '123,750 Gil', x = 8, y = 8 },
    },
    ['Stonega'] = {
        { npc = 'Hilkomu-Makimu', zone = 'Windurst Waters South', location = '(G-7)', notes = '1,191 Gil Windurst at least 2nd place in Conquest', x = 7, y = 7 },
        { npc = 'Chutarmire', zone = 'Selbina', location = '(H-9)', notes = '1,191 Gil', x = 8, y = 9 },
    },
    ['Stonega II'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '12,000 Gil', x = 8, y = 9 },
    },
    ['Stonega III'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '69,875 Gil', x = 8, y = 9 },
    },
    ['Stoneja'] = {
        { npc = 'Ezura-Romazura', zone = 'Windurst Waters (S)', location = '(H-8) (South Map)', notes = '168,150 Gil', x = 8, y = 8 },
    },
    ['Stonera'] = {
        { npc = 'Ledericus', zone = 'Western Adoulin', location = '(H-5)', notes = '7,476 Gil', x = 8, y = 5 },
    },
    ['Stonera II'] = {
        { npc = 'Ledericus', zone = 'Western Adoulin', location = '(H-5)', notes = '504,000 Gil', x = 8, y = 5 },
    },
    ['Stoneskin'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '7,181 Gil San d\'Oria must be 1st place in Conquest AND Must be San d\'Oria Citizen', x = 10, y = 8 },
        { npc = 'Kususu', zone = 'Port Windurst', location = '(H-8)', notes = '7,181 Gil Windurst must be 1st place in Conquest AND Must be Windurst Citizen', x = 8, y = 8 },
        { npc = 'Sororo', zone = 'Bastok Markets', location = '(H-5)', notes = '7,181 Gil Bastok must be 1st place in Conquest AND Must be Bastok Citizen', x = 8, y = 5 },
    },
    ['Stun'] = {
        { npc = 'Mamaroon', zone = 'Nashmau', location = '(H-7)', notes = '27,000 Gil', x = 8, y = 7 },
        { npc = 'Brave Ox', zone = 'Rabao', location = '(F-7)', notes = '32,200 Gil', x = 6, y = 7 },
    },
    ['Suiton: Ichi'] = {
        { npc = 'Jabbar', zone = 'Port Bastok', location = '(F-6)', notes = '1,561 Gil Tenshodo Guild Merchant Open from 1:00 - 23:00 daily', x = 6, y = 6 },
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '2,331 Gil', x = 10, y = 8 },
        { npc = 'Chiyo', zone = 'Norg', location = '(I-8)', notes = '1,747 Gil', x = 9, y = 8 },
    },
    ['Suiton: San'] = {
        { npc = 'Solby-Maholby', zone = 'Norg', location = '(H-9)', notes = '107,325 Gil', x = 8, y = 9 },
    },
    ['Swift Etude'] = {
        { npc = 'Harmodios', zone = 'Bastok Markets', location = '(K-10)', notes = '67,712 Gil Bastok at least 2nd place in Conquest', x = 11, y = 10 },
    },
    ['Sword Madrigal'] = {
        { npc = 'Boncort', zone = 'Northern San d\'Oria', location = '(F-8)', notes = '167 Gil', x = 6, y = 8 },
    },
    ['Teleport-Altep'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '34,656 Gil', x = 10, y = 8 },
    },
    ['Teleport-Dem'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '32,176 Gil', x = 10, y = 8 },
    },
    ['Teleport-Holla'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '32,176 Gil', x = 10, y = 8 },
    },
    ['Teleport-Mea'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '32,176 Gil', x = 10, y = 8 },
    },
    ['Teleport-Vahzl'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '34,656 Gil', x = 10, y = 8 },
    },
    ['Teleport-Yhoat'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '34,656 Gil', x = 10, y = 8 },
    },
    ['Thundaga'] = {
        { npc = 'Hilkomu-Makimu', zone = 'Windurst Waters South', location = '(G-7)', notes = '15,456 Gil Windurst at least 2nd place in Conquest', x = 7, y = 7 },
        { npc = 'Chutarmire', zone = 'Selbina', location = '(H-9)', notes = '15,456 Gil', x = 8, y = 9 },
    },
    ['Thundaga II'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '31,681 Gil', x = 8, y = 9 },
    },
    ['Thundaga III'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '144,000 Gil', x = 8, y = 9 },
    },
    ['Thundara'] = {
        { npc = 'Ledericus', zone = 'Western Adoulin', location = '(H-5)', notes = '54,600 Gil', x = 8, y = 5 },
    },
    ['Thundara II'] = {
        { npc = 'Ledericus', zone = 'Western Adoulin', location = '(H-5)', notes = '722,700 Gil', x = 8, y = 5 },
    },
    ['Thunder'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '3,334 Gil', x = 10, y = 8 },
        { npc = 'Aroro', zone = 'Port Windurst', location = '(H-8)', notes = '3,334 Gil', x = 8, y = 8 },
        { npc = 'Zaira', zone = 'Bastok Markets', location = '(H-5)', notes = '3,334 Gil', x = 8, y = 5 },
    },
    ['Thunder II'] = {
        { npc = 'Hilkomu-Makimu', zone = 'Windurst Waters South', location = '(G-7)', notes = '28,520 Gil', x = 7, y = 7 },
        { npc = 'Chutarmire', zone = 'Selbina', location = '(H-9)', notes = '28,520 Gil', x = 8, y = 9 },
    },
    ['Thunder III'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '45,930 Gil', x = 8, y = 9 },
        { npc = 'Mazween', zone = 'Aht Urhgan Whitegate', location = '(G-7)', notes = '45,930 Gil', x = 7, y = 7 },
    },
    ['Thunder IV'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '185,000 Gil', x = 8, y = 9 },
    },
    ['Thunderstorm'] = {
        { npc = 'Layton', zone = 'The Eldieme Necropolis (S)', location = '(J-8)', notes = '9,100 Gil', x = 10, y = 8 },
    },
    ['Tonko: Ichi'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '2,849 Gil', x = 10, y = 8 },
    },
    ['Tornado'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '56,250 Gil', x = 8, y = 9 },
    },
    ['Tornado II'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '129,180 Gil', x = 8, y = 9 },
    },
    ['Uncanny Etude'] = {
        { npc = 'Harmodios', zone = 'Bastok Markets', location = '(K-10)', notes = '78,200 Gil Bastok at least 2nd place in Conquest', x = 11, y = 10 },
    },
    ['Utsusemi: Ichi'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '13,133 Gil', x = 10, y = 8 },
    },
    ['Valor Minuet'] = {
        { npc = 'Hortense', zone = 'Bastok Markets', location = '(K-10)', notes = '22 Gil', x = 11, y = 10 },
    },
    ['Valor Minuet II'] = {
        { npc = 'Hortense', zone = 'Bastok Markets', location = '(K-10)', notes = '1,126 Gil', x = 11, y = 10 },
    },
    ['Valor Minuet III'] = {
        { npc = 'Hortense', zone = 'Bastok Markets', location = '(K-10)', notes = '5,667 Gil', x = 11, y = 10 },
    },
    ['Valor Minuet V'] = {
        { npc = 'Hortense', zone = 'Bastok Markets', location = '(K-10)', notes = '53,820 Gil', x = 11, y = 10 },
    },
    ['Viruna'] = {
        { npc = 'Hasim', zone = 'Lower Jeuno', location = '(H-9)', notes = '13,300 Gil', x = 8, y = 9 },
        { npc = 'Zafif', zone = 'Al Zahbi', location = '(J-8)', notes = '13,300 Gil', x = 10, y = 8 },
    },
    ['Vital Etude'] = {
        { npc = 'Harmodios', zone = 'Bastok Markets', location = '(K-10)', notes = '70,656 Gil Bastok at least 2nd place in Conquest', x = 11, y = 10 },
    },
    ['Vivacious Etude'] = {
        { npc = 'Manyny', zone = 'Windurst Woods', location = '(H-13)', notes = '2,208 Gil', x = 8, y = 13 },
        { npc = 'Leyla', zone = 'Port Jeuno', location = '(H-8)', notes = '2,400 Gil', x = 8, y = 8 },
    },
    ['Voidstorm'] = {
        { npc = 'Layton', zone = 'The Eldieme Necropolis (S)', location = '(J-8)', notes = '10,725 Gil', x = 10, y = 8 },
    },
    ['Warp'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '11,953 Gil', x = 10, y = 8 },
    },
    ['Warp II'] = {
        { npc = 'Amalasanda', zone = 'Lower Jeuno', location = '(J-8)', notes = '37,200 Gil', x = 10, y = 8 },
    },
    ['Water'] = {
        { npc = 'Regine', zone = 'Port San d\'Oria', location = '(J-8)', notes = '143 Gil', x = 10, y = 8 },
        { npc = 'Aroro', zone = 'Port Windurst', location = '(H-8)', notes = '143 Gil', x = 8, y = 8 },
        { npc = 'Zaira', zone = 'Bastok Markets', location = '(H-5)', notes = '143 Gil', x = 8, y = 5 },
    },
    ['Water Carol'] = {
        { npc = 'Yoskolo', zone = 'Lower Jeuno', location = '(I-8)', notes = '5,000 Gil', x = 9, y = 8 },
    },
    ['Water Carol II'] = {
        { npc = 'Valeriano', zone = 'Port Bastok', location = '(K-8)', notes = '28,520 Gil First Place nation in Conquest only', x = 11, y = 8 },
        { npc = 'Valeriano', zone = 'Southern San d\'Oria', location = '(I-9)', notes = '28,520 Gil First Place nation in Conquest only', x = 9, y = 9 },
        { npc = 'Valeriano', zone = 'Windurst Woods', location = '(H-10)', notes = '28,520 Gil First Place nation in Conquest only', x = 8, y = 10 },
    },
    ['Water II'] = {
        { npc = 'Hilkomu-Makimu', zone = 'Windurst Waters South', location = '(G-7)', notes = '8,280 Gil', x = 7, y = 7 },
        { npc = 'Chutarmire', zone = 'Selbina', location = '(H-9)', notes = '8,280 Gil', x = 8, y = 9 },
    },
    ['Water III'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '22,682 Gil', x = 8, y = 9 },
        { npc = 'Mazween', zone = 'Aht Urhgan Whitegate', location = '(G-7)', notes = '22,682 Gil', x = 7, y = 7 },
    },
    ['Water IV'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '116,000 Gil', x = 8, y = 9 },
    },
    ['Water Threnody'] = {
        { npc = 'Champalpieu', zone = 'Upper Jeuno', location = '(H-6)', notes = '420 Gil', x = 8, y = 6 },
    },
    ['Water V'] = {
        { npc = 'Ezura-Romazura', zone = 'Windurst Waters (S)', location = '(H-8) (South Map)', notes = '133,110 Gil', x = 8, y = 8 },
    },
    ['Watera'] = {
        { npc = 'Ledericus', zone = 'Western Adoulin', location = '(H-5)', notes = '21,000 Gil', x = 8, y = 5 },
    },
    ['Watera II'] = {
        { npc = 'Ledericus', zone = 'Western Adoulin', location = '(H-5)', notes = '530,265 Gil', x = 8, y = 5 },
    },
    ['Waterga'] = {
        { npc = 'Hilkomu-Makimu', zone = 'Windurst Waters South', location = '(G-7)', notes = '2,134 Gil Windurst at least 2nd place in Conquest', x = 7, y = 7 },
        { npc = 'Chutarmire', zone = 'Selbina', location = '(H-9)', notes = '2,134 Gil', x = 8, y = 9 },
    },
    ['Waterga II'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '13,050 Gil', x = 8, y = 9 },
    },
    ['Waterga III'] = {
        { npc = 'Susu', zone = 'Lower Jeuno', location = '(H-9)', notes = '82,250 Gil', x = 8, y = 9 },
    },
    ['Waterja'] = {
        { npc = 'Ezura-Romazura', zone = 'Windurst Waters (S)', location = '(H-8) (South Map)', notes = '176,700 Gil', x = 8, y = 8 },
    },
    ['Wind Carol'] = {
        { npc = 'Yoskolo', zone = 'Lower Jeuno', location = '(I-8)', notes = '5,940 Gil', x = 9, y = 8 },
    },
    ['Wind Carol II'] = {
        { npc = 'Valeriano', zone = 'Port Bastok', location = '(K-8)', notes = '30,912 Gil First Place nation in Conquest only', x = 11, y = 8 },
        { npc = 'Valeriano', zone = 'Southern San d\'Oria', location = '(I-9)', notes = '30,912 Gil First Place nation in Conquest only', x = 9, y = 9 },
        { npc = 'Valeriano', zone = 'Windurst Woods', location = '(H-10)', notes = '30,912 Gil First Place nation in Conquest only', x = 8, y = 10 },
    },
    ['Wind Threnody'] = {
        { npc = 'Champalpieu', zone = 'Upper Jeuno', location = '(H-6)', notes = '567 Gil', x = 8, y = 6 },
    },
    ['Windstorm'] = {
        { npc = 'Layton', zone = 'The Eldieme Necropolis (S)', location = '(J-8)', notes = '6,786 Gil', x = 10, y = 8 },
    },
    ['Yain: Ichi'] = {
        { npc = 'Solby-Maholby', zone = 'Norg', location = '(H-9)', notes = '140,319 Gil', x = 8, y = 9 },
    },
    ['Yurin: Ichi'] = {
        { npc = 'Solby-Maholby', zone = 'Norg', location = '(H-9)', notes = '82,075 Gil', x = 8, y = 9 },
    },
}
